### ISSUE TITLE
Are ok if I extract arduino-cli parts and publish it as a new library. Will fill a great void. Ar you can do it?

### ISSUE THREAD

**Issue by mfyuce** [luisllamasbinaburo/NppArduino#1]
Are ok if I extract arduino-cli parts and publish it as a new library. Will fill a great void. Ar you can do it?

**Comment by luisllamasbinaburo** [comment]
OK, It sounds a good idea
Here you are [Csharp Ardunino CLI](https://github.com/luisllamasbinaburo/CSharp_Arduino_CLI)
I make it a .NET Standard library, so it's should be compatible (not tested) with Windows and Linux

**Comment by mfyuce** [comment]
Thank you very much. Good works!
